# Atlas OS gaming tweaks
vm.max_map_count = 2147483642
vm.swappiness = 100
kernel.split_lock_mitigate = 0
kernel.sched_autogroup_enabled = 1
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fastopen = 3
